services:
  - type: web
    name: quest-bot
    env: node
    plan: free
    repo: https://github.com/kaizenrdebug/Quest-Helper.git
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: ~18
